import type { Metadata } from "next";
import SessionWrapper from "../components/SessionWrapper";
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html >
  );
}
